/** Keys the agent may propose. CRM-owned profile fields are deliberately excluded. */
export const AGENT_PROFILE_KEYS = [
  'service',
  'company',
  'sector',
  'location',
  'need',
  'currentSituation',
  'users',
  'productCount',
  'paymentNeeds',
  'shippingNeeds',
  'inventoryNeeds',
  'domainStatus',
  'corporateEmailNeeds',
  'integrations',
  'budget',
  'timeline',
  'lastObjection',
  'contactPreference',
] as const;

export const AGENT_DEFAULT_INTENTS = [
  'info_general',
  'consulta_servicio',
  'consulta_precio',
  'consulta_cobro_tienda',
  'consulta_pago_proyecto',
  'cotizacion',
  'agendar_cita',
  'solicitud_humano',
  'queja',
  'reclamo',
  'pago_fallido',
  'negociacion_especial',
  'info_producto',
  'interes_nava',
  'soporte',
  'otro',
] as const;
